# Settings.toml

debug_mode = false
log_level = "Debug"

[git]
credentials_file = "./Credentials.cf"

[app_specific]
# Level of logging: error, warn, info, debug, or trace.
log_level = "info"
# The interval, in seconds that we check for git updates
interval_seconds = 30 
# This determines weather we try to communicate with the artisan daemon on updates
register_with_aggregator = false